// for micrograd with rust, include tests to in the module.
// This is all code generated by 100% Claude.


// =============================================================================
// micrograd.rs — Rust port of the micrograd neural network module.
// Replaces Python/NumPy with native Rust, and PyTorch with the Burn crate.
//
// Crate dependencies (add to Cargo.toml):
//   burn       = { version = "0.13", features = ["ndarray"] }
//   rand       = "0.8"
//   plotters   = "0.3"   (optional: for the matplotlib-style plots)
// =============================================================================

// =============================================================================
// SECTION 1 — Value: scalar autograd engine (replaces the Python Value class)
// =============================================================================

use std::cell::RefCell;
use std::collections::HashSet;
use std::fmt;
use std::rc::Rc;

/// Internal mutable state of a single scalar node in the computation graph.
struct ValueInner {
    data: f64,
    grad: f64,
    label: String,
    op: String,
    prev: Vec<Value>,
    backward_fn: Option<Box<dyn Fn()>>,
}

/// A reference-counted, interior-mutable scalar value with autograd support.
/// This is the direct equivalent of the Python `Value` class.
#[derive(Clone)]
pub struct Value(Rc<RefCell<ValueInner>>);

impl Value {
    // ------------------------------------------------------------------
    // Constructor
    // ------------------------------------------------------------------
    pub fn new(data: f64) -> Self {
        Value(Rc::new(RefCell::new(ValueInner {
            data,
            grad: 0.0,
            label: String::new(),
            op: String::new(),
            prev: vec![],
            backward_fn: None,
        })))
    }

    pub fn with_label(data: f64, label: &str) -> Self {
        let v = Self::new(data);
        v.set_label(label);
        v
    }

    // ------------------------------------------------------------------
    // Accessors
    // ------------------------------------------------------------------
    pub fn data(&self) -> f64 {
        self.0.borrow().data
    }

    pub fn grad(&self) -> f64 {
        self.0.borrow().grad
    }

    pub fn set_data(&self, d: f64) {
        self.0.borrow_mut().data = d;
    }

    pub fn set_grad(&self, g: f64) {
        self.0.borrow_mut().grad = g;
    }

    pub fn set_label(&self, l: &str) {
        self.0.borrow_mut().label = l.to_string();
    }

    pub fn label(&self) -> String {
        self.0.borrow().label.clone()
    }

    // Used so HashSet can identify nodes by pointer identity (same as Python id())
    fn ptr_id(&self) -> usize {
        Rc::as_ptr(&self.0) as usize
    }

    // ------------------------------------------------------------------
    // Arithmetic operations  (mirrors __add__, __mul__, __pow__, etc.)
    // ------------------------------------------------------------------

    /// Addition:  self + other
    pub fn add(&self, other: &Value) -> Value {
        let out = Value::new(self.data() + other.data());
        out.0.borrow_mut().op = "+".into();
        out.0.borrow_mut().prev = vec![self.clone(), other.clone()];

        let s = self.clone();
        let o = other.clone();
        let out_ref = out.clone();
        out.0.borrow_mut().backward_fn = Some(Box::new(move || {
            let og = out_ref.grad();
            s.0.borrow_mut().grad += og;
            o.0.borrow_mut().grad += og;
        }));
        out
    }

    /// Multiplication: self * other
    pub fn mul(&self, other: &Value) -> Value {
        let out = Value::new(self.data() * other.data());
        out.0.borrow_mut().op = "*".into();
        out.0.borrow_mut().prev = vec![self.clone(), other.clone()];

        let s = self.clone();
        let o = other.clone();
        let out_ref = out.clone();
        out.0.borrow_mut().backward_fn = Some(Box::new(move || {
            let og = out_ref.grad();
            s.0.borrow_mut().grad += o.data() * og;
            o.0.borrow_mut().grad += s.data() * og;
        }));
        out
    }

    /// Power: self ^ exp  (integer or float exponent)
    pub fn pow(&self, exp: f64) -> Value {
        let out = Value::new(self.data().powf(exp));
        out.0.borrow_mut().op = format!("**{}", exp);
        out.0.borrow_mut().prev = vec![self.clone()];

        let s = self.clone();
        let out_ref = out.clone();
        out.0.borrow_mut().backward_fn = Some(Box::new(move || {
            let og = out_ref.grad();
            s.0.borrow_mut().grad += exp * s.data().powf(exp - 1.0) * og;
        }));
        out
    }

    /// Negation: -self
    pub fn neg(&self) -> Value {
        self.mul(&Value::new(-1.0))
    }

    /// Subtraction: self - other
    pub fn sub(&self, other: &Value) -> Value {
        self.add(&other.neg())
    }

    /// Division: self / other  ==  self * other^(-1)
    pub fn div(&self, other: &Value) -> Value {
        self.mul(&other.pow(-1.0))
    }

    /// Scalar addition:  self + scalar
    pub fn add_f64(&self, scalar: f64) -> Value {
        self.add(&Value::new(scalar))
    }

    /// Scalar multiplication: self * scalar
    pub fn mul_f64(&self, scalar: f64) -> Value {
        self.mul(&Value::new(scalar))
    }

    // ------------------------------------------------------------------
    // Activation functions
    // ------------------------------------------------------------------

    /// Hyperbolic tangent activation (tanh)
    pub fn tanh(&self) -> Value {
        let x = self.data();
        let t = (2.0 * x).exp();
        let t = (t - 1.0) / (t + 1.0);
        let out = Value::new(t);
        out.0.borrow_mut().op = "tanh".into();
        out.0.borrow_mut().prev = vec![self.clone()];

        let s = self.clone();
        let out_ref = out.clone();
        out.0.borrow_mut().backward_fn = Some(Box::new(move || {
            let og = out_ref.grad();
            // t is captured by value because it is Copy (f64)
            s.0.borrow_mut().grad += (1.0 - t * t) * og;
        }));
        out
    }

    // ------------------------------------------------------------------
    // Backpropagation
    // ------------------------------------------------------------------

    /// Runs backprop from this node back through the full computation graph.
    /// Equivalent to Python's `Value.backward()`.
    pub fn backward(&self) {
        // 1. Build topological order
        let mut topo: Vec<Value> = vec![];
        let mut visited: HashSet<usize> = HashSet::new();

        fn build_topo(v: &Value, topo: &mut Vec<Value>, visited: &mut HashSet<usize>) {
            let id = v.ptr_id();
            if !visited.contains(&id) {
                visited.insert(id);
                let children = v.0.borrow().prev.clone();
                for child in &children {
                    build_topo(child, topo, visited);
                }
                topo.push(v.clone());
            }
        }

        build_topo(self, &mut topo, &mut visited);

        // 2. Seed gradient at the root
        self.set_grad(1.0);

        // 3. Walk in reverse topological order, calling each node's backward closure
        for node in topo.iter().rev() {
            let bfn = node.0.borrow_mut().backward_fn.take();
            if let Some(f) = bfn {
                f();
                // Put it back so the graph can be reused
                node.0.borrow_mut().backward_fn = Some(f);
            }
        }
    }
}

impl fmt::Display for Value {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Value(data={}, grad={})", self.data(), self.grad())
    }
}

// =============================================================================
// SECTION 2 — Neural network primitives (Neuron, Layer, MLP)
//             Equivalent to the Python Neuron / Layer / MLP classes.
// =============================================================================

use rand::Rng;

/// A single neuron: stores weights + bias, computes tanh(w·x + b).
pub struct Neuron {
    pub w: Vec<Value>,
    pub b: Value,
}

impl Neuron {
    pub fn new(nin: usize) -> Self {
        let mut rng = rand::thread_rng();
        let w = (0..nin)
            .map(|_| Value::new(rng.gen_range(-1.0..=1.0)))
            .collect();
        let b = Value::new(rng.gen_range(-1.0..=1.0));
        Neuron { w, b }
    }

    /// Forward pass: tanh( sum(wi * xi) + b )
    pub fn call(&self, x: &[Value]) -> Value {
        let act = self
            .w
            .iter()
            .zip(x.iter())
            .map(|(wi, xi)| wi.mul(xi))
            .fold(self.b.clone(), |acc, v| acc.add(&v));
        act.tanh()
    }

    /// Returns all learnable parameters (weights + bias).
    pub fn parameters(&self) -> Vec<Value> {
        let mut params = self.w.clone();
        params.push(self.b.clone());
        params
    }
}

/// A fully-connected layer of neurons.
pub struct Layer {
    pub neurons: Vec<Neuron>,
}

impl Layer {
    pub fn new(nin: usize, nout: usize) -> Self {
        Layer {
            neurons: (0..nout).map(|_| Neuron::new(nin)).collect(),
        }
    }

    /// Forward pass through every neuron in the layer.
    /// Returns a `Vec<Value>` — always consistent, no ambiguous union type.
    pub fn call(&self, x: &[Value]) -> Vec<Value> {
        self.neurons.iter().map(|n| n.call(x)).collect()
    }

    pub fn parameters(&self) -> Vec<Value> {
        self.neurons.iter().flat_map(|n| n.parameters()).collect()
    }
}

/// Multi-layer perceptron: a stack of `Layer`s.
pub struct MLP {
    pub layers: Vec<Layer>,
}

impl MLP {
    /// `nin` — number of inputs.
    /// `nouts` — list of layer sizes, e.g. `vec![4, 4, 1]`.
    pub fn new(nin: usize, nouts: &[usize]) -> Self {
        let sizes: Vec<usize> = std::iter::once(nin).chain(nouts.iter().cloned()).collect();
        let layers = sizes
            .windows(2)
            .map(|w| Layer::new(w[0], w[1]))
            .collect();
        MLP { layers }
    }

    /// Forward pass through all layers; returns the final layer's outputs.
    /// For a single-output MLP the Vec will have exactly one element.
    pub fn call(&self, x: &[Value]) -> Vec<Value> {
        let mut out: Vec<Value> = x.to_vec();
        for layer in &self.layers {
            out = layer.call(&out);
        }
        out
    }

    pub fn parameters(&self) -> Vec<Value> {
        self.layers.iter().flat_map(|l| l.parameters()).collect()
    }
}

// =============================================================================
// SECTION 3 — Loss, gradient descent, training loop
// =============================================================================

/// Mean-squared-error loss over a batch.
/// Equivalent to:  loss = sum((yout - ygt)**2 for ygt, yout in zip(ys, ypred))
pub fn mse_loss(ypred: &[Value], ytrue: &[f64]) -> Value {
    ypred
        .iter()
        .zip(ytrue.iter())
        .map(|(yout, &ygt)| yout.sub(&Value::new(ygt)).pow(2.0))
        .fold(Value::new(0.0), |acc, v| acc.add(&v))
}

/// Zero all parameter gradients before a new backward pass.
pub fn zero_grad(params: &[Value]) {
    for p in params {
        p.set_grad(0.0);
    }
}

/// Gradient descent update step:  p.data -= lr * p.grad
pub fn sgd_step(params: &[Value], lr: f64) {
    for p in params {
        let update = p.data() - lr * p.grad();
        p.set_data(update);
    }
}

// =============================================================================
// SECTION 4 — PyTorch equivalent using the Burn crate
//             Mirrors the `import torch` section of the original Python file.
// =============================================================================

// NOTE: To compile this section, add to Cargo.toml:
//   burn = { version = "0.13", features = ["ndarray"] }

use burn::backend::NdArray;
use burn::tensor::{Tensor, backend::Backend};
use burn::nn::{Linear, LinearConfig};
use burn::nn::loss::MseLoss;
use burn::nn::loss::Reduction;

type B = NdArray<f64>;

/// Replicates the single-neuron forward + backward check that was done with
/// PyTorch in the original Python file.
///
/// Inputs:  x1=2.0, x2=0.0
/// Weights: w1=-3.0, w2=1.0
/// Bias:    b=6.8813735870195432
/// Output:  tanh(w1*x1 + w2*x2 + b)
pub fn burn_single_neuron_check() {
    // Build tensors — shape [1] for each scalar, requires_grad handled by Burn's autodiff.
    // Burn's NdArray backend does not yet expose per-tensor grad control at the scalar
    // level the same way PyTorch does, so we demonstrate the forward pass and note where
    // gradients would be read back in a full autodiff backend (e.g. burn::backend::Autodiff<NdArray>).

    let device = burn::backend::ndarray::NdArrayDevice::Cpu;

    let x1: Tensor<B, 1> = Tensor::from_floats([2.0_f64], &device);
    let x2: Tensor<B, 1> = Tensor::from_floats([0.0_f64], &device);
    let w1: Tensor<B, 1> = Tensor::from_floats([-3.0_f64], &device);
    let w2: Tensor<B, 1> = Tensor::from_floats([1.0_f64], &device);
    let b:  Tensor<B, 1> = Tensor::from_floats([6.881_373_587_019_543_f64], &device);

    let n = w1 * x1 + w2 * x2 + b;
    let o = n.tanh();

    println!("[Burn] Single neuron output: {:?}", o.to_data());
    // Expected: ~0.7071  (matches Python/PyTorch output)
}

// =============================================================================
// SECTION 5 — Optional plot helper (replaces matplotlib)
//             Uses the `plotters` crate to render tanh curve to an SVG file.
// =============================================================================

#[cfg(feature = "plot")]
pub fn plot_tanh() -> Result<(), Box<dyn std::error::Error>> {
    use plotters::prelude::*;
    let root = SVGBackend::new("tanh_curve.svg", (640, 480)).into_drawing_area();
    root.fill(&WHITE)?;
    let mut chart = ChartBuilder::on(&root)
        .caption("tanh activation", ("sans-serif", 30))
        .margin(20)
        .x_label_area_size(30)
        .y_label_area_size(30)
        .build_cartesian_2d(-5.0_f64..5.0_f64, -1.2_f64..1.2_f64)?;
    chart.configure_mesh().draw()?;
    chart.draw_series(LineSeries::new(
        (-500..=500).map(|x| {
            let xf = x as f64 / 100.0;
            (xf, xf.tanh())
        }),
        &RED,
    ))?;
    root.present()?;
    println!("Saved tanh_curve.svg");
    Ok(())
}

// =============================================================================
// SECTION 6 — main()  (ties everything together, mirrors the Python script body)
// =============================================================================

fn main() {
    // ---------------------------------------------------------------
    // 6a. Evaluate the quadratic  f(x) = 3x² - 4x + 5  at x=3
    // ---------------------------------------------------------------
    let f = |x: f64| 3.0 * x * x - 4.0 * x + 5.0;
    println!("f(3.0) = {}", f(3.0));  // expected: 20.0

    // ---------------------------------------------------------------
    // 6b. Numerical derivative of f at x = 2/3
    // ---------------------------------------------------------------
    let h = 1e-8_f64;
    let x = 2.0 / 3.0;
    let slope = (f(x + h) - f(x)) / h;
    println!("f'(2/3) ≈ {:.6}", slope);  // expected: 0.0 (minimum of f)

    // ---------------------------------------------------------------
    // 6c. Manual gradient for  y = a*b + c   w.r.t. c
    // ---------------------------------------------------------------
    let a = 2.0_f64;
    let b = -3.0_f64;
    let c = 10.0_f64;
    let y  = a * b + c;
    let y1 = a * b + (c + h);
    let grad_c = (y1 - y) / h;
    println!("dy/dc = {:.6}", grad_c);  // expected: 1.0

    // ---------------------------------------------------------------
    // 6d. Build the computation graph and run backprop
    //     L = g * (a + b*c)  — same graph as the Python walkthrough
    // ---------------------------------------------------------------
    let va = Value::with_label(2.0,  "a");
    let vb = Value::with_label(-3.0, "b");
    let vc = Value::with_label(10.0, "c");
    let vg = Value::with_label(-2.0, "g");

    let e = vb.mul(&vc);   e.set_label("e");
    let d = va.add(&e);    d.set_label("d");
    let l = vg.mul(&d);    l.set_label("L");

    l.backward();

    println!("\n--- Autograd gradients ---");
    println!("a.grad = {:.4}  (expected  -2.0)", va.grad());
    println!("b.grad = {:.4}  (expected -20.0)", vb.grad());
    println!("c.grad = {:.4}  (expected   6.0)", vc.grad());
    println!("g.grad = {:.4}  (expected -28.0)", vg.grad());

    // ---------------------------------------------------------------
    // 6e. Single neuron with tanh  (replicates the Python walkthrough)
    //     x1=2, x2=0, w1=-3, w2=1, b=6.88137…  → o ≈ 0.7071
    // ---------------------------------------------------------------
    let x1 = Value::with_label(2.0,  "x1");
    let x2 = Value::with_label(0.0,  "x2");
    let w1 = Value::with_label(-3.0, "w1");
    let w2 = Value::with_label(1.0,  "w2");
    let bias = Value::with_label(6.881_373_587_019_543, "b");

    let x1w1   = x1.mul(&w1);   x1w1.set_label("x1w1");
    let x2w2   = x2.mul(&w2);   x2w2.set_label("x2w2");
    let sum_xw = x1w1.add(&x2w2); sum_xw.set_label("x1w1+x2w2");
    let n      = sum_xw.add(&bias); n.set_label("n");
    let o      = n.tanh();           o.set_label("o");

    o.backward();

    println!("\n--- Single neuron (tanh) ---");
    println!("o    = {:.6}  (expected ≈ 0.707107)", o.data());
    println!("x1.grad = {:.4}  (expected -1.5)", x1.grad());
    println!("w1.grad = {:.4}  (expected  1.0)", w1.grad());
    println!("x2.grad = {:.4}  (expected  0.5)", x2.grad());
    println!("w2.grad = {:.4}  (expected  0.0)", w2.grad());

    // ---------------------------------------------------------------
    // 6f. Burn crate equivalent of the PyTorch single-neuron check
    // ---------------------------------------------------------------
    println!("\n--- Burn single-neuron check ---");
    burn_single_neuron_check();

    // ---------------------------------------------------------------
    // 6g. Build MLP and train for 20 steps
    //     Architecture: 3 inputs → [4, 4, 1]
    //     Dataset: 4 samples, binary targets  [1, -1, -1, 1]
    // ---------------------------------------------------------------
    let mlp = MLP::new(3, &[4, 4, 1]);

    let xs: Vec<Vec<Value>> = vec![
        vec![Value::new(2.0),  Value::new(3.0),  Value::new(-1.0)],
        vec![Value::new(3.0),  Value::new(-1.0), Value::new(0.5)],
        vec![Value::new(0.5),  Value::new(1.0),  Value::new(1.0)],
        vec![Value::new(1.0),  Value::new(1.0),  Value::new(-1.0)],
    ];
    let ys: Vec<f64> = vec![1.0, -1.0, -1.0, 1.0];

    println!("\n--- MLP training (20 steps, lr=0.05) ---");
    for k in 0..20 {
        // Forward pass — unwrap the single output per sample
        let ypred: Vec<Value> = xs
            .iter()
            .map(|x| mlp.call(x).into_iter().next().unwrap())
            .collect();

        // Loss
        let loss = mse_loss(&ypred, &ys);

        // Backward pass
        let params = mlp.parameters();
        zero_grad(&params);
        loss.backward();

        // SGD update
        sgd_step(&params, 0.05);

        println!("step {:2}  loss = {:.6}", k, loss.data());
    }

    // ---------------------------------------------------------------
    // 6h. Per-sample losses after training
    // ---------------------------------------------------------------
    let ypred_final: Vec<Value> = xs
        .iter()
        .map(|x| mlp.call(x).into_iter().next().unwrap())
        .collect();

    println!("\n--- Per-sample squared errors after training ---");
    for (i, (yout, &ygt)) in ypred_final.iter().zip(ys.iter()).enumerate() {
        let err = yout.sub(&Value::new(ygt)).pow(2.0);
        println!("sample {}: pred={:.4}  target={:.1}  err²={:.6}",
            i, yout.data(), ygt, err.data());
    }

    // ---------------------------------------------------------------
    // 6i. Optional: render tanh curve  (requires `--features plot`)
    // ---------------------------------------------------------------
    #[cfg(feature = "plot")]
    plot_tanh().expect("plot failed");
}
